### ISSUE TITLE
strata

### ISSUE THREAD

**Issue by tbalan** [tbalan/frailtyEM#12]
The idea is to add strata. 

Problem: how to deal with the Commenges Andersen test in this case?

**Comment by teddybalan** [comment]
C-A test has been made to work with strata as a separate function. 

Essentially the data set has to be split by the strata and then a lot of calculations have to go on with a big big lapply.

Should not be too complicated to do, would be nice to make some time for this.

**Comment by tbalan** [comment]
Making a whole big deal now
