### ISSUE TITLE
How to print the etimated baseline hazard?

### ISSUE THREAD

**Issue by DSChip** [tbalan/frailtyEM#81]
I fitted an emfrail model. I need to see the baseline hazards. What command/function I need to use?

**Comment by tbalan** [comment]
You can find the Breslow estimator in the hazard slot of the fitted object:

`m_gamma <- emfrail(formula = Surv(time, status) ~  rx + sex + cluster(litter),
                   data =  rats)`
`m_gamma$hazard`

also, see, see `?predict.emfrail` for more options regarding the (cumulative) baseline hazard.

**Comment by DSChip** [comment]
Thank you for your quick reply. May I ask for additional info on this?
My dataset "foo" has 598 row and 4 columns:
`> dim(foo)
[1] 598   4`

Column "GBF" contains 0 for "No failure" and 1 for "failure".
The number of failures is

`> sum(foo$GBF)
[1] 386`

yet the length of the vector of hazards is

`> length(M0$hazard)
[1] 261`

I'm not sure how these 261 estimated hazards are linked back to my dataset. Can you please provide more info in this?

**Comment by tbalan** [comment]
The Breslow estimator is non-negative at every event time point (`GBF == 1` in your case) and is 0 at the other time points. The estimates in `$hazard` correspond to the event time points in `$tev`.
